add CI and tests

diff --git a/.github/actions/shared/verify_installation/action.yml b/.github/actions/shared/verify_installation/action.yml
--- a/.github/actions/shared/verify_installation/action.yml
+++ b/.github/actions/shared/verify_installation/action.yml
@@ -130,6 +130,14 @@ runs:
               echo '================================================================================' >> $file_name
             done
         done
+        
+        restart_count=$(kubectl get pod "$pod" -n ${{inputs.namespace}} -o jsonpath="{.status.containerStatuses[0].restartCount}")
+        if [[ "$restart_count" -gt 0 ]]; then
+          echo "🔁 Previous logs (before restart) for pod: $pod"
+          if ! kubectl logs "$pod" -n ${{inputs.namespace}} --previous; then
+            echo "⚠️ Could not fetch previous logs for $pod"
+          fi
+        fi
 
     - name: Generate artifact name
       if: always()
