test workflow

diff --git a/.github/workflows/dev-mvn-docker-build.yaml b/.github/workflows/dev-mvn-docker-build.yaml
--- a/.github/workflows/dev-mvn-docker-build.yaml
+++ b/.github/workflows/dev-mvn-docker-build.yaml
@@ -31,57 +31,136 @@ permissions:
 
 env:
   TAG_NAME: ${{ github.event.release.tag_name || github.ref }}
+  additional-mvn-args: "-Dstage=release -Dstage=test -Denable-analyzers=true -Dpg.jdbc.Url=jdbc:postgresql://localhost:5432/datasets -Dpg.jdbc.User=datasets -Dpg.jdbc.Password=datasets -Dpg.jdbc.Dialect=com.querydsl.sql.PostgreSQLTemplates -Dgridfs.database=dsgridfs -Dspring.data.mongodb.uri=mongodb://localhost:27017/dsgridfs -Dgridfs.port=27017 -Dgridfs.user=dsuser -Dgridfs.password=dspass"
 
 jobs:
   mvn-snapshot-deploy:
-    uses: ./.github/workflows/re-maven-snapshot-deploy.yaml
-    with:
-      java-version: "21"
-      additional-mvn-args: "-Dstage=release -Dstage=test -Denable-analyzers=true -Dpg.jdbc.Url=jdbc:postgresql://localhost:5432/datasets -Dpg.jdbc.User=datasets -Dpg.jdbc.Password=datasets -Dpg.jdbc.Dialect=com.querydsl.sql.PostgreSQLTemplates -Dgridfs.database=dsgridfs -Dspring.data.mongodb.uri=mongodb://localhost:27017/dsgridfs -Dgridfs.port=27017 -Dgridfs.user=dsuser -Dgridfs.password=dspass"
-      target-store: "maven-central"
-    secrets:
-      maven-username: ${{ secrets.MAVEN_USER }}
-      maven-token: ${{ secrets.MAVEN_PASSWORD }}
-      gpg-passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}
-      gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
-
-  build-and-push:
     runs-on: ubuntu-latest
-    needs: mvn-snapshot-deploy
-
     steps:
-      - name: Checkout Repository
-        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+      - name: "Checkout code"
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+
+      - name: Checkout pipeline
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          ref: 'main'
+          repository: 'Netcracker/qubership-testing-platform-helm-hook-helper'
+          path: 'qubership-testing-platform-helm-hook-helper'
+
+      - name: Postgres up
+        uses: netcracker/qubership-testing-platform-helm-hook-helper/.github/actions/databases/postgres_for_build@main
+        with:
+          postgresql_user: datasets
+          postgresql_password: datasets
+          postgresql_database: datasets
+          postgresql_admin_password: postgres
+
+      - name: Mongo up
+        uses: netcracker/qubership-testing-platform-helm-hook-helper/.github/actions/databases/mongo_for_build@main
+
+      - name: Maven Docker build
+        id: maven_build
+        uses: netcracker/qubership-workflow-hub/actions/maven-snapshot-deploy@9538833017019ab6bbc2138d3034778dfe3a5d1f # v2.0.6
+        with:
+          java-version: "21"
+          additional-mvn-args: ${{ env.additional-mvn-args }}
+          target-store: "github"
+          upload-artifact: 'true'
+          maven-username: ${{ github.ACTOR }}
+          maven-token: ${{ secrets.GITHUB_TOKEN }}
+          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
+          gpg-passphrase: ${{ secrets.GPG-PASSPHRASE }}
+
+  load-docker-build-components:
+    runs-on: ubuntu-latest
+    outputs:
+      component: ${{ steps.load_component.outputs.components }}
+      platforms: ${{ steps.load_component.outputs.platforms }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
         with:
           persist-credentials: false
 
+      - name: Load Docker Configuration
+        id: load_component
+        run:  |
+          verify=$(cat "$GITHUB_WORKSPACE/.github/docker-build-config.json" | jq '
+          def verify_structure:
+          .components as $components
+          | .platforms as $platforms
+          | ($components | type == "array")
+          and (all($components[]; has("name") and has("file") and has("context")))
+          and ($platforms | type == "string");
+          verify_structure
+          | if . then true else false end
+          ')
+          if [ ${verify} == 'true' ]; then
+            echo "✅ $GITHUB_WORKSPACE/.github/docker-build-config.json file is valid"
+            components=$(jq -c ".components" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
+            platforms=$(jq -c ".platforms" "$GITHUB_WORKSPACE/.github/docker-build-config.json")
+          else
+            echo "❗ $GITHUB_WORKSPACE/.github/docker-build-config.json file is invalid"
+            echo "❗ $GITHUB_WORKSPACE/.github/docker-build-config.json file is invalid" >> $GITHUB_STEP_SUMMARY
+            exit 1
+          fi
+          echo "components=${components}" >> $GITHUB_OUTPUT
+          echo "platforms=${platforms}" >> $GITHUB_OUTPUT
+
+  build-and-push:
+    runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        component: ${{ fromJson(needs.load-docker-build-components.outputs.component) }}
+    needs: [ mvn-snapshot-deploy, load-docker-build-components ]
+    steps:
+      - name: Checkout Repository
+        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
+        with:
+          persist-credentials: false
+
+      - name: Replace slash in service branch
+        id: replace_slash
+        run: |
+          if [[ -n "$GITHUB_HEAD_REF" ]]; then
+            service_branch="$GITHUB_HEAD_REF"
+          else
+            service_branch="$GITHUB_REF_NAME"
+          fi
+          service_branch="${service_branch//\//_}"
+          
+          echo "Branch is: $service_branch"
+          echo "SERVICE_BRANCH=$service_branch" >> $GITHUB_ENV
+
       - name: Metadata
         id: metadata
-        uses: netcracker/qubership-workflow-hub/actions/metadata-action@9319676b7d20b423a2e0943a0ac08da07d615998 #v1.0.6
+        uses: netcracker/qubership-workflow-hub/actions/metadata-action@396774180000abdb825cbf150b56cc59c6913db8 #v2.0.5
         with:
           default-template: '{{ref-name}}-{{timestamp}}'
 
-      - name: Build and Publish Docker Image For Environments
-        uses: netcracker/qubership-workflow-hub/actions/docker-action@9319676b7d20b423a2e0943a0ac08da07d615998 #v1.0.6
+      - name: Build and Publish Docker Image
+        id: docker_build
+        uses: netcracker/qubership-workflow-hub/actions/docker-action@396774180000abdb825cbf150b56cc59c6913db8 #v2.0.5
         with:
           ref: ${{ github.ref }}
           dry-run: false
-          tags: ${{steps.metadata.outputs.result}}
+          tags: ${{steps.metadata.outputs.result}}, ${{ env.SERVICE_BRANCH }}_latest
           download-artifact: true
-          custom-image-name: qubership-testing-platform-datasets
           download-artifact-path: build-context
-          component: '[{"name": "qubership-testing-platform-datasets", "file": "./Dockerfile", "context": "."}]'
+          component: ${{ toJson(matrix.component) }}
+          platforms: ${{ needs.load-docker-build-components.outputs.platforms }}
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Build and Publish Docker Image For Transfer
-        uses: netcracker/qubership-workflow-hub/actions/docker-action@9319676b7d20b423a2e0943a0ac08da07d615998 #v1.0.6
-        with:
-          ref: ${{ github.ref }}
-          dry-run: false
-          tags: ${{steps.metadata.outputs.result}}
-          download-artifact: false
-          custom-image-name: qubership-testing-platform-datasets-transfer
-          component: '[{"name": "qubership-testing-platform-datasets-transfer", "file": "docker-transfer/Dockerfile", "context": "."}]'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+  run-tests:
+    needs: [ build-and-push ]
+    uses: netcracker/qubership-testing-platform-helm-hook-helper/.github/workflows/deploy-run-tests.yaml@main
+    with:
+      repository_name: 'qubership-testing-platform-datasets'
+      service_name: 'atp-datasets'
+      namespace: 'datasets'
+      pipeline_branch: 'main'
+      postgres: enable
+      enable_test: enable
